#!/bin/sh

# Install Rust
yes 1 | curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

source "$HOME/.cargo/env"

if command -v pacman
then
  yes | sudo pacman -S base-devel pkg-config
fi

# Install sccache
# cargo install sccache
# RUSTC_WRAPPER=sccache cargo build

# Install Programs
cargo install nu
cargo install coreutils
cargo install starship
cargo install exa
cargo install du-dust
cargo install bat
cargo install zellij
cargo install ripgrep
cargo install helix
cargo install bacon
cargo install ncspot
cargo install porsmo
cargo install speedtest-rs

dotfiles_path=$HOME/.dotfiles

# createlink () {
  # if [[ ! -f $1 ]]; then
    # ln -s $dotfiles_path/$1 $HOME/$2
  # fi
# }

# createlink  "gitconfig"   ".gitconfig"
# createlink  "zshrc"       ".zshrc"
# createlink  "helix"       ".config/helix"
# createlink  "freshfetch"  ".config/freshfetch"

sudo chsh arlo /Users/Arlo/.cargo/bin/nu
