#!/bin/sh

dotfiles_path=$HOME/.dotfiles

createlink () {
  if [[ ! -f $1 ]]; then
    ln -s $dotfiles_path/$1 $HOME/$2
  fi
}

createlink  "gitconfig"   ".gitconfig"
createlink  "zshrc"       ".zshrc"
createlink  "sshconfig"   ".ssh/config"
createlink  "helix"       ".config/helix"
createlink  "freshfetch"  ".config/freshfetch"
