#!/bin/sh

# Install Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# Install sccache
cargo install sccache
RUSTC_WRAPPER=sccache cargo build

# Install Programs
cargo install nu
cargo install coreutils
cargo install starship
cargo install exa
cargo install du-dust
cargo install bat
cargo install zellij
cargo install ripgrep
cargo install helix
cargo install bacon
cargo install ncspot
cargo install porsmo
cargo install speedtest-rs

dotfiles_path=$HOME/.dotfiles

createlink () {
  if [[ ! -f $1 ]]; then
    ln -s $dotfiles_path/$1 $HOME/$2
  fi
}

createlink  "gitconfig"   ".gitconfig"
createlink  "zshrc"       ".zshrc"
createlink  "sshconfig"   ".ssh/config"
createlink  "helix"       ".config/helix"
createlink  "freshfetch"  ".config/freshfetch"

chsh nu
