# [[language]]
name = "javascript"
auto-format = true
scope = "source.js"
injection-regex = "^(js|javascript)$"
file-types = ["js", "mjs"]
shebangs = ["node"]
roots = []
comment-token = "//"
language-server = { command = "typescript-language-server", args = ["--stdio"] }
indent = { tab-width = 4, unit = " "}

[[language]]
name = "css"
auto-format = true
scope = "source.css"
injection-regex = "^(css)$"
file-types = ["css", "scss"]
shebangs = []
roots = []
comment-token = "/**/"
indent = { tab-width = 4, unit = " " }

[[language]]
name = "html"
auto-format = true
scope = "source.html"
injection-regex = "^(html|htm)$"
file-types = ["html", "htm"]
shebangs = []
roots = []
comment-token = "<!-- -->"
indent = { tab-width = 4, unit = " " }
