theme = "gruvbox"

[editor]
line-number = "relative"
mouse = true
true-color = true

auto-completion = true
auto-save = true
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]

[keys.insert]
C-c = "normal_mode"

[editor.statusline]
left = ["mode", "file-name", "file-type"]
separator = ":"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true
character = "┊" # Some characters that work well: "╎" " ▏", "┆", "┊", "⸽"
skip-levels = 1